name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Build Docker image
      run: docker build -t sample-app -f Dockerfile.dev .

    - name: Run tests
      run: docker run -e CI=true sample-app npm run test -- --coverage --watchAll=false
